services:
  - type: web
    name: shukarsh
    runtime: docker
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_PATH
        value: /data/db.sqlite3
      - key: UPLOADS_DIR
        value: /data/uploads
      - key: ADMIN_PASSWORD
        sync: false
